### PR TITLE
Card ui design updated

### PR DESCRIPTION
**Pull request by manikmmalhotra**
i've updated the ui design of the card layout

### CODE REVIEW

**Comment by abhi211199** [comment]
@manikmmalhotra Please share a screenshot showing the changes!

**Comment by manikmmalhotra** [comment]
23f3d449-be04-4d7f-8d8e-e4929e22bc14

**Comment by manikmmalhotra** [comment]
also I've encountered more issues can I add them in your issues column...?

**Comment by abhi211199** [comment]
@manikmmalhotra Woah! It's a great UI refactoring! Great work! Thanks for contributing!
Also, feel free to add up more issues!

**Pull request merged**
